FROM rod_catch_returns/frontend-base AS fmt

USER root

# Install ClamAV
RUN apk add --no-cache clamav clamav-daemon \
    && freshclam

# Update virus database
RUN freshclam

# Ensure required ClamAV directories exist and have correct permissions
RUN mkdir -p /run/clamav /var/lib/clamav && \
    chown -R clamav:clamav /run/clamav /var/lib/clamav

# Start ClamAV then start app
ENTRYPOINT ["sh", "-c", "clamd & exec pm2-dev ecosystem.config.yml"]
