'use strict'

/**
 * The entry point of the rod catch returns web service. This is a hapi web server
 * and uses glue to compose the server.
 *
 */

require('dotenv').config()

const Glue = require('glue')
const Nunjucks = require('nunjucks')
const Uuid = require('uuid')
const Joi = require('joi')
const Crypto = require('crypto')

const { logger } = require('defra-logging-facade')
const AuthorizationSchemes = require('./src/lib/authorization-schemes')
const AuthorizationStrategies = require('./src/lib/authorization-strategies')
const EnvironmentSchema = require('./environment-schema')
const CacheDecorator = require('./src/lib/cache-decorator')

const manifest = {

  // Configure Hapi server and server-caching subsystem
  server: {
    port: process.env.PORT || 3000,
    cache: [
      {
        engine: require('catbox-redis'),
        host: process.env.REDIS_HOSTNAME,
        port: process.env.REDIS_PORT,
        partition: 'server-cache'
      }
    ]
  },

  // Register plugins
  register: {
    plugins: [
      /*
       * Using the DEFRA logging package
       * See: https://github.com/DEFRA/defra-logging-facade
       */
      {
        plugin: require('defra-logging-facade').HapiErrorLoggerPlugin
      },
      /*
       * Static file and directory handlers plugin for hapi.js
       * See https://www.npmjs.com/package/inert
       */
      {
        plugin: require('inert')
      },

      /*
       * Templates rendering plugin support for hapi.js
       * See https://www.npmjs.com/package/vision
       */
      {
        plugin: require('vision')
      },

      /*
       * Plug in for cookie based authentication
       * See https://www.npmjs.com/package/hapi-auth-cookie
       */
      {
        plugin: require('hapi-auth-cookie'),
        options: {
          mode: 'required'
        }
      },

      /*
       * Add a rudimentary health check
       * hit /health and check status 200
       * See: https://www.npmjs.com/package/hapi-alive
       */
      {
        plugin: require('hapi-alive'),
        options: {
          responses: {
            healthy: {
              message: 'Healthy'
            },
            unhealthy: {
              statusCode: 400
            }
          }
        }
      },

      /*
       * Plugin for serving up robots.txt
       * See https://www.npmjs.com/package/hapi-robots and
       * https://en.wikipedia.org/wiki/Robots_exclusion_standard
       */
      {
        plugin: require('hapi-robots'),
        options: {
          // will disallow everyone from every path:
          '*': ['/']
        }
      },

      /*
       * To print routes on startup change showStart to true
       * See https://www.npmjs.com/package/blipp
       */
      {
        plugin: require('blipp'),
        options: {
          showStart: false
        }
      },

      /*
       * Clean up any input
       * See: https://www.npmjs.com/package/disinfect
       */
      {
        plugin: require('disinfect'),
        options: {
          disinfectQuery: true,
          disinfectParams: true,
          disinfectPayload: true
        }
      },

      /*
       * Plugin for CSRF tokens
       * See https://www.npmjs.com/package/crumb
       */
      {
        plugin: require('crumb'),
        options: {
          key: 'rcr2018',
          cookieOptions: {
            isSecure: process.env.HTTPS === 'true' || false,
            isHttpOnly: true
          },
          logUnauthorized: true
        }
      }
    ]
  }
}

const options = {
  relativeTo: __dirname
}

;(async () => {
  try {
    /**
     * Test that the environment is set up correctly
     */
    Joi.validate(process.env, EnvironmentSchema, { allowUnknown: true }, (err) => {
      if (err) {
        throw new Error('Schema validation error: ' + err.message)
      }
    })

    const server = await Glue.compose(manifest, options)
    /*
     * Set up the nunjunks rendering engine and include the new gov.uk
     * design system templates and components so that the macros are accessible
     * directly in the templates.
     *
     * Note that vision caches compiled templates according to the isCached flag and so the
     * watch flag in the prepare function is set to false,
     * see https://github.com/hapijs/vision/issues/75
     *
     * The options supplied to the nunjunks processor in the prepare function are generated by the
     * vision template rendering support and hapi itself
     */
    server.views({
      engines: {
        html: {
          compile: function (src, options) {
            const template = Nunjucks.compile(src, options.environment)
            return function (context) {
              return template.render(context)
            }
          },
          prepare: (options, next) => {
            options.compileOptions.environment = Nunjucks.configure(options.path, { watch: false })
            return next()
          }
        }
      },
      isCached: process.env.NODE_ENV !== 'development',
      relativeTo: __dirname,
      path: [
        'src/views',
        'node_modules/govuk-frontend/',
        'node_modules/govuk-frontend/components/'
      ],

      // Set up the common view data
      context: () => {
        return {
          pgid: Uuid.v4()
        }
      }
    })

    // Set up the route handlers for static resources
    server.route({
      method: 'GET',
      path: '/public/{param*}',
      config: {
        auth: false
      },
      handler: {
        directory: {
          path: 'public'
        }
      }
    })

    // Point the server plugin cache to an application cache to hold authenticated session data
    server.app.cache = server.cache({
      segment: 'sessions',
      expiresIn: process.env.SESSION_TTL_MS
    })

    server.auth.scheme('active-dir-scheme', AuthorizationSchemes.activeDirScheme)
    server.auth.scheme('licence-scheme', AuthorizationSchemes.licenceScheme)
    server.auth.strategy('active-dir-strategy', 'active-dir-scheme')
    server.auth.strategy('licence-strategy', 'licence-scheme')
    server.auth.strategy('session', 'cookie', AuthorizationStrategies.sessionCookie)
    server.auth.default('session')

    /*
     * Plugin to automatically load the routes based on their file location
     * See https://www.npmjs.com/package/hapi-router. Run last so the default authentication
     * strategy can be registered first
     */
    await server.register({
      plugin: require('hapi-router'),
      options: {
        routes: process.env.CONTEXT === 'FMT' ? './src/routes/*.js' : './src/routes/angler.js'
      }
    })

    /*
     * Decorator to make access to the session cache available as
     * simple setters and getters hiding the session key.
     */
    server.decorate('request', 'cache', CacheDecorator)

    /*
     * Test that cryptographic support is enabled on the build
     */
    try {
      require('crypto')
    } catch (err) {
      logger.error('Crypto support disabled: ' + err)
      process.exit(1)
    }

    // Start the server
    await server.start()

    // Set a random cache key good for 30 years - shared between the nodes
    if (!await server.app.cache.get('hub-identity')) {
      logger.info('Assigning a new hub identity')
      await server.app.cache.set('hub-identity', Crypto.randomBytes(16), 1000 * 3600 * 24 * 365 * 30)
    }

    // Handle shutdown gracefully
    process.on('SIGINT', async () => {
      logger.info('Stopping server...')
      const err = await server.stop({ timeout: 10000 })
      logger.info('Stopped')
      process.exit((err) ? 1 : 0)
    })

    // Print the banner
    require('figlet')('Rod Catch Returns', function (err, data) {
      if (err) {
        return
      }
      console.log(data)
      logger.info(`Server started at ${server.info.uri}`)
    })
  } catch (err) {
    logger.error(err)
    process.exit(1)
  }
})()
